// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeEncoding(arg1:string):Promise<void>;

export function GetDirectoryTree(arg1:string):Promise<Array<main.FileNode>>;

export function GetParentDir(arg1:string):Promise<string>;

export function InitializeFile():Promise<void>;

export function LoadFile(arg1:string):Promise<void>;

export function OpenDirectory():Promise<void>;

export function SetPrettyPrint(arg1:boolean):Promise<void>;
