// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectoryTree(arg1) {
  return window['go']['main']['App']['GetDirectoryTree'](arg1);
}

export function GetParentDir(arg1) {
  return window['go']['main']['App']['GetParentDir'](arg1);
}

export function InitializeFile() {
  return window['go']['main']['App']['InitializeFile']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}
